/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArdhanaAgencyRouteImport } from './routes/ardhana-agency'
import { Route as ArdhanaDigitalRouteImport } from './routes/ardhana-digital'
import { Route as ArdhanaEventRouteImport } from './routes/ardhana-event'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArdhanaAgencyRoute = ArdhanaAgencyRouteImport.update({
  id: '/ardhana-agency',
  path: '/ardhana-agency',
  getParentRoute: () => rootRouteImport,
} as any)
const ArdhanaDigitalRoute = ArdhanaDigitalRouteImport.update({
  id: '/ardhana-digital',
  path: '/ardhana-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const ArdhanaEventRoute = ArdhanaEventRouteImport.update({
  id: '/ardhana-event',
  path: '/ardhana-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ardhana-agency': typeof ArdhanaAgencyRoute
  '/ardhana-digital': typeof ArdhanaDigitalRoute
  '/ardhana-event': typeof ArdhanaEventRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ardhana-agency': typeof ArdhanaAgencyRoute
  '/ardhana-digital': typeof ArdhanaDigitalRoute
  '/ardhana-event': typeof ArdhanaEventRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ardhana-agency': typeof ArdhanaAgencyRoute
  '/ardhana-digital': typeof ArdhanaDigitalRoute
  '/ardhana-event': typeof ArdhanaEventRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ardhana-agency'
    | '/ardhana-digital'
    | '/ardhana-event'
    | '/contact'
    | '/gallery'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ardhana-agency'
    | '/ardhana-digital'
    | '/ardhana-event'
    | '/contact'
    | '/gallery'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ardhana-agency'
    | '/ardhana-digital'
    | '/ardhana-event'
    | '/contact'
    | '/gallery'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArdhanaAgencyRoute: typeof ArdhanaAgencyRoute
  ArdhanaDigitalRoute: typeof ArdhanaDigitalRoute
  ArdhanaEventRoute: typeof ArdhanaEventRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ardhana-agency': {
      id: '/ardhana-agency'
      path: '/ardhana-agency'
      fullPath: '/ardhana-agency'
      preLoaderRoute: typeof ArdhanaAgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ardhana-digital': {
      id: '/ardhana-digital'
      path: '/ardhana-digital'
      fullPath: '/ardhana-digital'
      preLoaderRoute: typeof ArdhanaDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ardhana-event': {
      id: '/ardhana-event'
      path: '/ardhana-event'
      fullPath: '/ardhana-event'
      preLoaderRoute: typeof ArdhanaEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArdhanaAgencyRoute: ArdhanaAgencyRoute,
  ArdhanaDigitalRoute: ArdhanaDigitalRoute,
  ArdhanaEventRoute: ArdhanaEventRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
